version: '3.9'

services:
  express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=password1234
      - PGDATABASE=EcommerceDB
      - PGPORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: EcommerceDB
    ports:
      - "5432:5432"

volumes:
  postgres-data:
